# Generated by Django 5.2.14 on 2026-05-28 19:15

import WebApps.applib.models.books
import WebApps.applib.models.loans
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.TextField(db_column='fullName')),
                ('nationality', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['fullName'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('publishYear', models.IntegerField(blank=True, db_column='publishYear', null=True, validators=[WebApps.applib.models.books.validate_publish_year])),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copyNumber', models.IntegerField(db_column='copyNumber')),
                ('barcode', models.TextField(unique=True)),
                ('physicalCondition', models.TextField(blank=True, db_column='physicalCondition', default='BUENO', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.RESTRICT, to='applib.book')),
            ],
            options={
                'db_table': 'book_copies',
                'ordering': ['book', 'copyNumber'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.TextField(db_column='firstName')),
                ('lastName', models.TextField(db_column='lastName')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isAdmin', models.BooleanField(db_column='isAdmin', default=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_modified', to='applib.user')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['lastName', 'firstName', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loanDate', models.DateField(db_column='loanDate', default=django.utils.timezone.now)),
                ('dueDate', models.DateField(db_column='due_date', default=WebApps.applib.models.loans.get_default_due_date)),
                ('loanStatus', models.TextField(db_column='loan_status', default='Activo')),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('returnDate', models.DateField(blank=True, db_column='returnDate', null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book_copy', models.ForeignKey(db_column='book_copy_id', on_delete=django.db.models.deletion.RESTRICT, to='applib.bookcopy')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_modified', to='applib.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='applib.user')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['loanDate', 'loanStatus', 'user', 'book_copy'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.TextField(db_column='categoryName')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_modified', to='applib.user')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['categoryName'],
            },
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_created', to='applib.user'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_modified', to='applib.user'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='applib.book')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='applib.category')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_cats_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_cats_modified', to='applib.user')),
            ],
            options={
                'db_table': 'books_categories',
                'ordering': ['book', 'category'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_created', to='applib.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_modified', to='applib.user'),
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='applib.author')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='applib.book')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_books_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_books_modified', to='applib.user')),
            ],
            options={
                'db_table': 'authors_books',
                'ordering': ['book', 'author'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_created', to='applib.user'),
        ),
        migrations.AddField(
            model_name='author',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_modified', to='applib.user'),
        ),
        migrations.AddConstraint(
            model_name='bookcopy',
            constraint=models.UniqueConstraint(fields=('book', 'copyNumber'), name='unique_book_copy'),
        ),
        migrations.AddConstraint(
            model_name='bookcategory',
            constraint=models.UniqueConstraint(fields=('book', 'category'), name='unique_book_category'),
        ),
        migrations.AddConstraint(
            model_name='authorbook',
            constraint=models.UniqueConstraint(fields=('author', 'book'), name='unique_author_book'),
        ),
    ]
