# Generated by Django 5.2.14 on 2026-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0002_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', through='applib.BookCategory', to='applib.category'),
        ),
    ]
