# Generated by Django 5.2.14 on 2026-05-28 14:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.TextField(db_column='fullName')),
                ('nationality', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('publishYear', models.IntegerField(blank=True, db_column='publishYear', null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copyNumber', models.IntegerField(db_column='copyNumber')),
                ('physicalCondition', models.TextField(blank=True, db_column='physicalCondition', null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='applib.book')),
            ],
            options={
                'db_table': 'book_copies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.TextField(db_column='firstName')),
                ('lastName', models.TextField(db_column='lastName')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_modified', to='applib.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loanDate', models.DateField(db_column='loanDate', default=django.utils.timezone.now)),
                ('returnDate', models.DateField(blank=True, db_column='returnDate', null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_copy', models.ForeignKey(db_column='book_copy_id', on_delete=django.db.models.deletion.RESTRICT, to='applib.bookcopy')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_modified', to='applib.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, to='applib.user')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.TextField(db_column='categoryName')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_modified', to='applib.user')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_created', to='applib.user'),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_modified', to='applib.user'),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='applib.book')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='applib.category')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_cats_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_cats_modified', to='applib.user')),
            ],
            options={
                'db_table': 'books_categories',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_created', to='applib.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_modified', to='applib.user'),
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, to='applib.author')),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='applib.book')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_books_created', to='applib.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_books_modified', to='applib.user')),
            ],
            options={
                'db_table': 'authors_books',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_created', to='applib.user'),
        ),
        migrations.AddField(
            model_name='author',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors_modified', to='applib.user'),
        ),
    ]
