# Generated by Django 5.2.14 on 2026-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='applib.AuthorBook', to='applib.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', through='applib.BookCategory', to='applib.category'),
        ),
    ]
