# Generated by Django 5.2.14 on 2026-07-02 05:12

import WebApps.applib.models.loans
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applib', '0002_book_authors_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loanDate',
            field=models.DateField(db_column='loanDate', default=WebApps.applib.models.loans.get_current_date),
        ),
    ]
